import JSZip from "jszip";
import { getSession } from "@/lib/store";

export async function GET(_request: Request, { params }: { params: Promise<{ sessionId: string }> }) {
  const { sessionId } = await params;
  const session = getSession(sessionId);
  if (!session?.skillDraft?.markdown && !session?.existingSkill) {
    return new Response("No skill available", { status: 404 });
  }
  const zip = new JSZip();
  zip.file("SKILL.md", session.skillDraft?.markdown || session.existingSkill || "");
  zip.file(
    "README.md",
    "# Design Skill\n\nGenerated by the local Design SKILL.md Generator. Place this folder in your Codex skills directory when ready.\n"
  );
  zip.file("examples/sample.html", session.sampleHtml || "<!doctype html><html><body>No sample generated.</body></html>");
  for (const asset of session.assets) {
    const safeName = asset.name.replace(/[^\w.\-]+/g, "_");
    if (asset.content) zip.file(`assets/${safeName}.txt`, asset.content);
  }
  const bytes = await zip.generateAsync({ type: "uint8array" });
  return new Response(Buffer.from(bytes), {
    headers: {
      "content-type": "application/zip",
      "content-disposition": 'attachment; filename="design-skill.zip"'
    }
  });
}
